development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  # url: redis://localhost:6379/1
  # channel_prefix: Connect_Four_production
  url: redis://redistogo:21af2b3bc45387163d1a1e65654260db@cod.redistogo.com:11223
